# Generated by Django 5.0.6 on 2024-06-19 16:47

from django.db import migrations



def add_initial_sports(apps, schema_editor):
    Sport = apps.get_model('backend', 'Sport')
    sports = [
        {'name': 'gaelic football'},
        {'name': 'hurling'},
        {'name': 'camogie'},
        {'name': 'rugby'},
        {'name': 'soccer'},
        {'name': 'hockey'},
        {'name': 'basketball'},
    ]
    for sport in sports:
        Sport.objects.create(**sport)
    

class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0001_initial'),  # Ensure this matches your initial migration
    ]
    operations = [
        migrations.RunPython(add_initial_sports),
    ]