# Generated by Django 5.0.6 on 2024-06-24 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_add_initial_sports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("coach", "Coach"),
                    ("player", "Player"),
                    ("parent", "Parent"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ParentPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "player"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("parent", "player")},
            },
        ),
    ]
