# Generated by Django 5.0.6 on 2024-06-20 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_add_initial_sports"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("player_id", models.CharField(max_length=255)),
                (
                    "coach_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coached_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sport_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.sport"
                    ),
                ),
                (
                    "team_category_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.teamcategory",
                    ),
                ),
            ],
        ),
    ]
