# Generated by Django 5.0.6 on 2024-06-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_add_initial_sports"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sport",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="sport",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sports",
                to="backend.workspace",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sport",
            unique_together={("name", "workspace")},
        ),
    ]
