# Generated by Django 5.0.6 on 2024-07-01 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_alter_sport_unique_together_alter_sport_workspace_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                ("note_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("note", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SessionsImpactsOverview",
            fields=[
                ("session_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("max_lin_impact", models.BigIntegerField()),
                ("max_rot_impact", models.BigIntegerField()),
                ("avg_lin_impact", models.BigIntegerField()),
                ("avg_rot_impact", models.BigIntegerField()),
                ("cumulative_lin_impact", models.BigIntegerField()),
                ("cumulative_rot_impact", models.BigIntegerField()),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="backend.notes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionImpacts",
            fields=[
                ("impact_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField()),
                ("linear_impact", models.BigIntegerField()),
                ("rotational_impact", models.BigIntegerField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impacts",
                        to="backend.sessionsimpactsoverview",
                    ),
                ),
            ],
        ),
    ]
