# Generated by Django 5.0.6 on 2024-06-21 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="sport_id",
            new_name="sport",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="team_category_id",
            new_name="team_category",
        ),
        migrations.RemoveField(
            model_name="team",
            name="coach_id",
        ),
        migrations.RemoveField(
            model_name="team",
            name="player_id",
        ),
        migrations.AddField(
            model_name="team",
            name="coach",
            field=models.ForeignKey(
                default=3,
                limit_choices_to={"user_type": "coach"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coached_teams",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="players",
            field=models.ManyToManyField(
                limit_choices_to={"user_type": "player"},
                related_name="teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
