# Generated by Django 5.0.6 on 2024-07-01 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_notes_sessionsimpactsoverview_sessionimpacts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SessionImpacts",
            new_name="SessionImpact",
        ),
    ]
