# Generated by Django 5.0.6 on 2024-06-21 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_rename_sport_id_team_sport_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="coach",
        ),
        migrations.AddField(
            model_name="team",
            name="coaches",
            field=models.ManyToManyField(
                limit_choices_to={"user_type": "coach"},
                related_name="teams_as_coach",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
