# Generated by Django 5.0.6 on 2024-06-25 09:46
from django.db import migrations, models

def set_default_workspace(apps, schema_editor):
    CustomUser = apps.get_model('backend', 'CustomUser')
    Workspace = apps.get_model('backend', 'Workspace')
    default_workspace = Workspace.objects.get_or_create(name='Default Workspace')

    for user in CustomUser.objects.filter(workspace__isnull=True):
        user.workspace = default_workspace
        user.save()

class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_workspace_customuser_workspace_and_more"),
    ]

    operations = [migrations.RunPython(set_default_workspace),]
