# Generated by Django 5.0.6 on 2024-06-25 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_auto_20240625_1046"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="backend.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parentplayer",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_player_relationships",
                to="backend.workspace",
            ),
        ),
    ]
