# Generated by Django 5.0.6 on 2024-06-21 14:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_remove_team_coach_team_coaches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="players",
            field=models.ManyToManyField(
                limit_choices_to={"user_type": "player"},
                related_name="teams_as_player",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
