# Generated by Django 5.0.6 on 2024-06-25 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_alter_customuser_workspace_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sport",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sports",
                to="backend.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="backend.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teamcategory",
            name="workspace",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_categories",
                to="backend.workspace",
            ),
            preserve_default=False,
        ),
    ]
