# Generated by Django 5.0.6 on 2024-06-26 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_sport_workspace_team_workspace_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="backend.workspace",
            ),
        ),
    ]
