# Generated by Django 5.0.6 on 2024-06-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_alter_customuser_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
