# Generated by Django 5.0.6 on 2024-06-27 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sport",
            unique_together={("name", "workspace")},
        ),
    ]
