# Generated by Django 5.0.6 on 2024-06-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_alter_sport_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sport",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
