# Generated by Django 5.0.6 on 2024-06-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_alter_sport_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sport",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="sport",
            name="global_sport",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name="sport",
            unique_together={("name", "workspace", "global_sport")},
        ),
    ]
